FROM fedora:31

RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    python3-tox \
    python3-stomppy \
    python3-jsonpath-rw \
    python3-fedmsg \
    findutils \
    && dnf clean all

VOLUME /src
WORKDIR /src
CMD ["tox", "-r", "-e", "py37,coverage,flake8,bandit"]
