FROM centos:7

RUN yum -y install epel-release && \
    yum -y install \
    --nogpgcheck \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    python-jsonpath-rw \
    python-pip \
    python-tox \
    stomppy \
    python2-fedmsg \
    && yum clean all
# We currently require newer versions of these Python packages for the tests
RUN pip install --upgrade pip tox && pip install -I "more-itertools<6.0.0"
VOLUME /src
WORKDIR /src
CMD ["tox", "-r", "-e", "py27,coverage,flake8,bandit"]
